MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  RPN:
    PRE_NMS_TOP_N_TEST: 6000
    POST_NMS_TOP_N_TEST: 1000
  ROI_BOX_HEAD:
    NUM_CLASSES: 3
DATASETS:
  TRAIN: ("seed_train",)
  # VALIDATE: ("seed_train","seed_val","seed_test")
  TEST: ("seed_test",)
  STRATEGY: 1
DATALOADER: 
  SIZE_DIVISIBILITY: 1
SOLVER:
  BASE_LR: 0.01
  WEIGHT_DECAY: 0.0001
  STEPS: (24000, 32000)
  MAX_ITER: 2000
  CHECKPOINT_PERIOD: 100
  IMS_PER_BATCH: 2
TEST:
  IMS_PER_BATCH: 2
OUTPUT_DIR: ../faster_RCNN_R_50_C4_strat1
